version: '3.3'
name: technical
services:
   technical-postgres:
    container_name: technical-postgres-db
    image: postgres
    environment:
      POSTGRES_USER: ${DATA_BASE_USER_NAME}
      POSTGRES_PASSWORD: ${DATA_BASE_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
    ports:
      - '${DATA_BASE_PORT}:5432'
    restart: unless-stopped
    networks:
      - technical-network
networks:
  technical-network:
    driver: bridge
